//! Drama shot editor, placeholder layout, versions, and video-history persistence.

use rusqlite::{params, OptionalExtension};
use serde_json::{json, Map, Value};

use crate::{
    error::{AppError, AppResult},
    mapping,
    value::{json_text, new_id, now, row_to_json, string, GENERATING, NOT_GENERATED, SUCCEEDED},
};

use super::Repository;

/// Immutable inputs captured with a video-version row so later work is based on the media state the creator saw.
pub(crate) struct ShotVersionInput {
    /// Editable video prompt at the time this version was enqueued.
    pub prompt: String,
    /// Rich prompt with each referenced image URL frozen for later version reuse.
    pub prompt_rich: Value,
    /// Structured prompt metadata captured alongside the original prompt.
    pub structured: Value,
    /// Selected video provenance when this is a refinement-derived video version.
    pub refinement: Option<ShotVideoRefinement>,
}

/// Persisted provenance for a video generated by refining one completed history item.
pub(crate) struct ShotVideoRefinement {
    /// The completed historical version selected by the creator for this refinement.
    pub source_version_id: String,
    /// The selected version's frozen playable media URL passed back to the video provider.
    pub source_video_url: String,
}

impl Repository {
    /// Insert a shot directly below the selected shot while renumbering only its episode's trailing rows.
    pub fn create_shot(&self, drama_id: &str, values: Map<String, Value>) -> AppResult<Value> {
        let after_id = string(&values, "after_shot_id", "");
        if after_id.is_empty() {
            return Err(AppError::BadRequest("after_shot_id 不能为空".to_owned()));
        }
        let id = new_id();
        self.db.with_connection(|connection| {
            let after = connection.query_row("SELECT * FROM drama_shots WHERE id=?1 AND drama_id=?2", params![after_id, drama_id], row_to_json).optional()?
                .ok_or_else(|| AppError::NotFound(format!("Shot not found: {after_id}")))?;
            let episode_id = after["episode_id"].as_str().unwrap_or("episode:1").to_owned();
            let index = after["shot_index"].as_i64().unwrap_or(1);
            let timestamp = now();
            connection.execute("UPDATE drama_shots SET shot_index=shot_index+1,updated_at=?1 WHERE drama_id=?2 AND episode_id=?3 AND shot_index>?4", params![timestamp, drama_id, episode_id, index])?;
            connection.execute(
                "INSERT INTO drama_shots (id,drama_id,episode_id,episode_name,episode_sort_order,shot_index,title,original_text,duration_seconds,prompt,prompt_rich_json,status,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,10,?9,?10,?11,?12,?12)",
                params![id, drama_id, episode_id, after["episode_name"].as_str().unwrap_or("第1集"), after["episode_sort_order"].as_i64().unwrap_or(1), index + 1, string(&values,"title","未命名分镜"), string(&values,"original_text",""), string(&values,"prompt",""), json_text(values.get("prompt_rich").unwrap_or(&json!([]))), NOT_GENERATED, timestamp],
            )?;
            Ok(())
        })?;
        self.get_shot(drama_id, &id)
    }

    /// Return one shot scoped to its project, including restored rich-prompt and history fields.
    pub fn get_shot(&self, drama_id: &str, shot_id: &str) -> AppResult<Value> {
        self.db.with_connection(|connection| {
            connection
                .query_row(
                    "SELECT * FROM drama_shots WHERE id=?1 AND drama_id=?2",
                    params![shot_id, drama_id],
                    row_to_json,
                )
                .optional()?
                .map(mapping::shot)
                .ok_or_else(|| AppError::NotFound(format!("Shot not found: {shot_id}")))
        })
    }

    /// Update source, prompt, duration, references, and first/last frames from the editor.
    pub fn update_shot(
        &self,
        drama_id: &str,
        shot_id: &str,
        values: Map<String, Value>,
    ) -> AppResult<Value> {
        self.get_shot(drama_id, shot_id)?;
        self.db.with_connection(|connection| {
            if let Some(title) = values.get("title").and_then(Value::as_str) {
                if title.trim().is_empty() { return Err(AppError::BadRequest("分镜标题不能为空".to_owned())); }
                connection.execute("UPDATE drama_shots SET title=?1,updated_at=?2 WHERE id=?3 AND drama_id=?4", params![title.trim(), now(), shot_id, drama_id])?;
            }
            for key in ["original_text", "prompt", "prompt_template_version"] {
                if let Some(value) = values.get(key).and_then(Value::as_str) { connection.execute(&format!("UPDATE drama_shots SET {key}=?1,updated_at=?2 WHERE id=?3 AND drama_id=?4"), params![value, now(), shot_id, drama_id])?; }
            }
            if let Some(value) = values.get("duration_seconds").and_then(Value::as_i64) {
                if !(3..=15).contains(&value) { return Err(AppError::BadRequest("分镜时长需在 3 至 15 秒之间".to_owned())); }
                connection.execute("UPDATE drama_shots SET duration_seconds=?1,updated_at=?2 WHERE id=?3 AND drama_id=?4", params![value, now(), shot_id, drama_id])?;
            }
            if let Some(nodes) = values.get("prompt_rich") {
                let mut references = Vec::new();
                for id in nodes
                    .as_array()
                    .into_iter()
                    .flatten()
                    .filter(|node| node["type"] == "reference")
                    .filter_map(|node| node["asset_id"].as_str())
                {
                    if !references.contains(&id) {
                        references.push(id);
                    }
                }
                connection.execute(
                    "UPDATE drama_shots SET prompt_rich_json=?1,reference_asset_ids_json=?2,updated_at=?3 WHERE id=?4 AND drama_id=?5",
                    params![json_text(nodes), json_text(&json!(references)), now(), shot_id, drama_id],
                )?;
            }
            for (key, column) in [("reference_asset_ids", "reference_asset_ids_json"), ("placeholder_placements", "placeholder_placements_json"), ("structured", "structured_json")] {
                if let Some(value) = values.get(key) { connection.execute(&format!("UPDATE drama_shots SET {column}=?1,updated_at=?2 WHERE id=?3 AND drama_id=?4"), params![json_text(value), now(), shot_id, drama_id])?; }
            }
            if let Some(value) = values.get("first_last_frames") {
                let raw = connection.query_row("SELECT structured_json FROM drama_shots WHERE id=?1 AND drama_id=?2", params![shot_id, drama_id], |row| row.get::<_, String>(0))?;
                let mut structured: Map<String, Value> = serde_json::from_str(&raw).unwrap_or_default();
                structured.insert("first_last_frames".to_owned(), value.clone());
                connection.execute("UPDATE drama_shots SET structured_json=?1,updated_at=?2 WHERE id=?3 AND drama_id=?4", params![json_text(&Value::Object(structured)), now(), shot_id, drama_id])?;
            }
            Ok(())
        })?;
        self.get_shot(drama_id, shot_id)
    }

    /// Save a placeholder layout without enqueuing a media request.
    pub fn save_placeholder_layout(
        &self,
        drama_id: &str,
        shot_id: &str,
        values: Map<String, Value>,
    ) -> AppResult<Value> {
        if string(&values, "shot_id", shot_id) != shot_id {
            return Err(AppError::BadRequest("请求分镜与地址不匹配".to_owned()));
        }
        let scene_id = string(&values, "scene_asset_id", "");
        if scene_id.is_empty() {
            return Err(AppError::BadRequest("请选择场景素材".to_owned()));
        }
        self.db.with_connection(|connection| {
            if connection.execute("UPDATE drama_shots SET placeholder_scene_asset_id=?1,placeholder_placements_json=?2,updated_at=?3 WHERE id=?4 AND drama_id=?5", params![scene_id, json_text(values.get("placements").unwrap_or(&json!([]))), now(), shot_id, drama_id])? == 0 {
                return Err(AppError::NotFound(format!("Shot not found: {shot_id}")));
            }
            Ok(())
        })?;
        self.get_shot(drama_id, shot_id)
    }

    /// Return a partial-refresh payload containing normalized shots and grouped episodes.
    pub fn list_shots(&self, drama_id: &str) -> AppResult<(Vec<Value>, Vec<Value>)> {
        self.db.with_connection(|connection| {
            self.assert_drama(drama_id)?;
            let mut shots = self.shots_for(connection, drama_id)?;
            self.attach_shot_versions(connection, drama_id, &mut shots)?;
            let episodes = mapping::episodes(&shots);
            Ok((shots, episodes))
        })
    }

    /// Delete one shot, stop its still-active tasks, and compact remaining episode ordering.
    pub fn delete_shot(&self, drama_id: &str, shot_id: &str) -> AppResult<Value> {
        let shot = self.get_shot(drama_id, shot_id)?;
        self.db.with_connection(|connection| {
            let episode = shot["episode_id"].as_str().unwrap_or_default();
            let index = shot["shot_index"].as_i64().unwrap_or(1);
            let transaction = connection.unchecked_transaction()?;
            transaction.execute("UPDATE generation_tasks SET status='已取消',completed_at=?1,finished_at=?1,stage='分镜已删除' WHERE drama_id=?2 AND resource_id=?3 AND status='生成中'", params![now(), drama_id, shot_id])?;
            transaction.execute("DELETE FROM drama_shots WHERE id=?1 AND drama_id=?2", params![shot_id, drama_id])?;
            transaction.execute("UPDATE drama_shots SET shot_index=shot_index-1,updated_at=?1 WHERE drama_id=?2 AND episode_id=?3 AND shot_index>?4", params![now(), drama_id, episode, index])?;
            transaction.commit()?;
            Ok(json!({"status":"deleted", "id":shot_id}))
        })
    }

    /// Create a durable video-history row before a provider request begins, enabling restarts and cancellation.
    pub fn create_shot_version(
        &self,
        drama_id: &str,
        shot_id: &str,
        task_id: &str,
        prompt: &str,
    ) -> AppResult<Value> {
        self.create_shot_version_with_input(
            drama_id,
            shot_id,
            task_id,
            ShotVersionInput {
                prompt: prompt.to_owned(),
                prompt_rich: json!([]),
                structured: json!({}),
                refinement: None,
            },
        )
    }

    /// Create one immutable history row before provider work starts, retaining prompt and refinement provenance.
    pub fn create_shot_version_with_input(
        &self,
        drama_id: &str,
        shot_id: &str,
        task_id: &str,
        input: ShotVersionInput,
    ) -> AppResult<Value> {
        let ShotVersionInput {
            prompt,
            prompt_rich,
            structured,
            refinement,
        } = input;
        let (source_version_id, source_video_url) = refinement
            .map(|value| (Some(value.source_version_id), Some(value.source_video_url)))
            .unwrap_or((None, None));
        self.db.with_connection(|connection| {
            let number: i64 = connection.query_row("SELECT COALESCE(MAX(version_no),0)+1 FROM drama_shot_versions WHERE shot_id=?1", [shot_id], |row| row.get(0))?;
            let id = new_id();
            connection.execute("INSERT INTO drama_shot_versions (id,drama_id,shot_id,task_id,version_no,status,prompt,prompt_rich_json,structured_json,refinement_source_version_id,source_video_url,refinement_prompt,created_at) VALUES (?1,?2,?3,?4,?5,'生成中',?6,?7,?8,?9,?10,'',?11)", params![id, drama_id, shot_id, task_id, number, prompt, json_text(&prompt_rich), json_text(&structured), source_version_id, source_video_url, now()])?;
            connection.query_row("SELECT * FROM drama_shot_versions WHERE id=?1", [id], row_to_json).map_err(Into::into)
        })
    }

    /// Read one history version scoped to its shot before a micro-adjustment creates a dependent version.
    pub fn get_shot_version(
        &self,
        drama_id: &str,
        shot_id: &str,
        version_id: &str,
    ) -> AppResult<Value> {
        self.db.with_connection(|connection| {
            connection
                .query_row(
                    "SELECT * FROM drama_shot_versions WHERE id=?1 AND drama_id=?2 AND shot_id=?3",
                    params![version_id, drama_id, shot_id],
                    row_to_json,
                )
                .optional()?
                .map(mapping::shot_version)
                .ok_or_else(|| AppError::NotFound(format!("Video version not found: {version_id}")))
        })
    }

    /// Save feedback on the selected history row so future refinements reopen with the creator's last instruction.
    pub fn set_shot_version_refinement_prompt(
        &self,
        drama_id: &str,
        shot_id: &str,
        version_id: &str,
        prompt: &str,
    ) -> AppResult<()> {
        self.db.with_connection(|connection| {
            if connection.execute(
                "UPDATE drama_shot_versions SET refinement_prompt=?1 WHERE id=?2 AND drama_id=?3 AND shot_id=?4 AND status=?5 AND COALESCE(video_url,'')<>''",
                params![prompt, version_id, drama_id, shot_id, SUCCEEDED],
            )? == 0 {
                return Err(AppError::BadRequest("只能微调已生成完成的视频".to_owned()));
            }
            Ok(())
        })
    }

    /// Finalize one persisted video version; the version table is the sole source for video history cards.
    pub fn finish_shot_version(
        &self,
        drama_id: &str,
        shot_id: &str,
        version_id: &str,
        status: &str,
        video_url: Option<&str>,
        error: Option<&str>,
    ) -> AppResult<Value> {
        self.db.with_connection(|connection| {
            connection.execute("UPDATE drama_shot_versions SET status=?1,video_url=?2,error_message=?3,progress=100,completed_at=?4 WHERE id=?5 AND drama_id=?6 AND shot_id=?7", params![status, video_url, error, now(), version_id, drama_id, shot_id])?;
            connection.execute("UPDATE drama_shots SET status=?1,updated_at=?2 WHERE id=?3 AND drama_id=?4", params![status, now(), shot_id, drama_id])?;
            connection.query_row("SELECT * FROM drama_shot_versions WHERE id=?1", [version_id], row_to_json).map_err(Into::into)
        })
    }

    /// Store provider task identity and progress on the immutable version row while it awaits a remote poll.
    pub fn schedule_shot_version_poll(
        &self,
        drama_id: &str,
        shot_id: &str,
        version_id: &str,
        provider_task_id: &str,
        progress: i64,
    ) -> AppResult<()> {
        self.db.with_connection(|connection| {
            connection.execute("UPDATE drama_shot_versions SET provider_task_id=?1,progress=?2 WHERE id=?3 AND drama_id=?4 AND shot_id=?5 AND status='生成中'", params![provider_task_id,progress.clamp(0,99),version_id,drama_id,shot_id])?;
            Ok(())
        })
    }

    /// Mark a version cancelled without appending a playable history record for an unfinished provider job.
    pub fn cancel_shot_version(
        &self,
        drama_id: &str,
        shot_id: &str,
        version_id: &str,
    ) -> AppResult<()> {
        self.db.with_connection(|connection| {
            connection.execute("UPDATE drama_shot_versions SET status='已取消',completed_at=?1 WHERE id=?2 AND drama_id=?3 AND shot_id=?4 AND status='生成中'", params![now(),version_id,drama_id,shot_id])?;
            Ok(())
        })
    }

    /// Return historical versions used by the video picker and task-card UI.
    pub fn shot_versions(&self, drama_id: &str, shot_id: &str) -> AppResult<Vec<Value>> {
        self.db.with_connection(|connection| {
            let mut statement = connection.prepare("SELECT * FROM drama_shot_versions WHERE drama_id=?1 AND shot_id=?2 ORDER BY version_no DESC")?;
            let rows = statement
                .query_map(params![drama_id,shot_id], row_to_json)?
                .collect::<Result<Vec<_>, _>>()?;
            Ok(rows)
        })
    }

    /// Remove a selected history card and its companion version record after its media file has been collected.
    pub fn delete_shot_video(
        &self,
        drama_id: &str,
        shot_id: &str,
        video_id: &str,
    ) -> AppResult<Value> {
        self.db.with_connection(|connection| {
            let raw = connection
                .query_row(
                    "SELECT historical_videos_json FROM drama_shots WHERE id=?1 AND drama_id=?2",
                    params![shot_id, drama_id],
                    |row| row.get::<_, String>(0),
                )
                .optional()?
                .ok_or_else(|| AppError::NotFound(format!("Shot not found: {shot_id}")))?;
            let history: Vec<Value> = serde_json::from_str(&raw).unwrap_or_default();
            let kept: Vec<Value> = history
                .into_iter()
                .filter(|item| item["id"].as_str() != Some(video_id))
                .collect();
            connection.execute(
                "UPDATE drama_shots SET historical_videos_json=?1,updated_at=?2 WHERE id=?3",
                params![json_text(&Value::Array(kept)), now(), shot_id],
            )?;
            connection.execute(
                "DELETE FROM drama_shot_versions WHERE id=?1 AND drama_id=?2 AND shot_id=?3",
                params![video_id, drama_id, shot_id],
            )?;
            Ok(json!({"status":"deleted", "id":video_id}))
        })
    }

    /// Persist the latest local/model quality check without replacing the editable prompt itself.
    pub fn set_shot_quality(
        &self,
        drama_id: &str,
        shot_id: &str,
        quality: Value,
    ) -> AppResult<Value> {
        let status = quality["status"].as_str().unwrap_or("通过");
        let issues = quality["issues"].clone();
        self.db.with_connection(|connection| {
            if connection.execute("UPDATE drama_shots SET quality_json=?1,quality_status=?2,quality_issues_json=?3,updated_at=?4 WHERE id=?5 AND drama_id=?6", params![json_text(&quality),status,json_text(&issues),now(),shot_id,drama_id])? == 0 { return Err(AppError::NotFound(format!("Shot not found: {shot_id}"))); }
            Ok(())
        })?;
        self.get_shot(drama_id, shot_id)
    }

    /// Atomically store one generated rich prompt, its parsed structure, and the template provenance used for it.
    pub fn save_generated_shot_prompt(
        &self,
        drama_id: &str,
        shot_id: &str,
        prompt: &str,
        nodes: &[Value],
        structured: &Value,
        references: &[String],
        template_id: Option<&str>,
        template_version: &str,
    ) -> AppResult<Value> {
        self.db.with_connection(|connection| {
            let (has_successful_video, has_generating_video): (bool, bool) = connection.query_row(
                "SELECT EXISTS(SELECT 1 FROM drama_shot_versions WHERE drama_id=?1 AND shot_id=?2 AND status=?3 AND COALESCE(video_url,'')<>''), EXISTS(SELECT 1 FROM drama_shot_versions WHERE drama_id=?1 AND shot_id=?2 AND status=?4)",
                params![drama_id, shot_id, SUCCEEDED, GENERATING],
                |row| Ok((row.get::<_, i64>(0)? != 0, row.get::<_, i64>(1)? != 0)),
            )?;
            let status = if has_successful_video {
                SUCCEEDED
            } else if has_generating_video {
                GENERATING
            } else {
                NOT_GENERATED
            };
            if connection.execute(
                "UPDATE drama_shots SET prompt=?1,prompt_rich_json=?2,structured_json=?3,reference_asset_ids_json=?4,prompt_template_id=?5,prompt_template_version=?6,quality_status='未检查',quality_issues_json='[]',status=?7,updated_at=?8 WHERE id=?9 AND drama_id=?10",
                params![prompt,json_text(&Value::Array(nodes.to_vec())),json_text(structured),json_text(&json!(references)),template_id,template_version,status,now(),shot_id,drama_id],
            )? == 0 {
                return Err(AppError::NotFound(format!("Shot not found: {shot_id}")));
            }
            Ok(())
        })?;
        self.get_shot(drama_id, shot_id)
    }

    /// Reflect the durable automatic quality task in the editable shot without replacing its last result.
    pub fn mark_shot_quality_pending(&self, drama_id: &str, shot_id: &str) -> AppResult<()> {
        self.db.with_connection(|connection| {
            if connection.execute(
                "UPDATE drama_shots SET quality_status='检查中',quality_issues_json='[]',updated_at=?1 WHERE id=?2 AND drama_id=?3",
                params![now(), shot_id, drama_id],
            )? == 0 {
                return Err(AppError::NotFound(format!("Shot not found: {shot_id}")));
            }
            Ok(())
        })
    }

    /// Mark a shot while a prompt/video/quality worker is active or returns to a terminal state.
    pub fn set_shot_status(&self, drama_id: &str, shot_id: &str, status: &str) -> AppResult<()> {
        self.db.with_connection(|connection| {
            if connection.execute(
                "UPDATE drama_shots SET status=?1,updated_at=?2 WHERE id=?3 AND drama_id=?4",
                params![status, now(), shot_id, drama_id],
            )? == 0
            {
                return Err(AppError::NotFound(format!("Shot not found: {shot_id}")));
            }
            Ok(())
        })
    }
}
