"""Repair endpoint documentation lines generated by the first splitter pass."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
for relative in ("backend/src/api/router.py", "backend/src/api/game_routes.py"):
    path = ROOT / relative
    lines = path.read_text().splitlines()
    fixed = []
    for line in lines:
        if line.lstrip().startswith('"""Frontend route:') and not line.rstrip().endswith('"""'):
            line = line + '"""'
        fixed.append(line)
    path.write_text("\n".join(fixed).rstrip() + "\n")
