//! Bounded three-episode storyboard planning for the numbered screenplay generated by long-form expansion.
use serde_json::{json, Value};
use std::{collections::HashSet, thread};

use crate::{
    error::{AppError, AppResult},
    skills,
    value::NOT_GENERATED,
};

use super::{expansion::support, retry::immediate_language_retry_delay, DurableWorker};

const DECOMPOSITION_START_PROGRESS: i64 = 65;
const DECOMPOSITION_END_PROGRESS: i64 = 75;
const STREAM_PROGRESS_REPORT_CHARS: usize = 1_000;

impl DurableWorker {
    /// Plan every persisted long-form episode in three-episode model batches for faster first-token feedback.
    pub(super) fn long_form_plan(
        &self,
        task_id: &str,
        project: &Value,
        screenplay: &str,
    ) -> AppResult<Value> {
        self.run_decomposition_batch_pipeline(task_id, project, screenplay)
    }

    pub(super) fn stream_decomposition_batch(
        &self,
        task_id: &str,
        model: Option<&str>,
        project: &Value,
        batch: &[support::Episode],
        known_character_names: &[String],
        batch_index: usize,
        batch_count: usize,
        progress: i64,
        completed_received_chars: usize,
        decomposer_instruction: &str,
        enable_web: bool,
    ) -> AppResult<Option<String>> {
        let stage = batch_stage(batch, batch_index, batch_count, 0, completed_received_chars);
        let system = format!(
            "{}\n\n你是短剧分镜总监。严格按照用户要求返回合法 JSON，不要 Markdown。\n\n拆解执行规范：\n{}",
            skills::drama_agent_system()?,
            decomposer_instruction,
        );
        let prompt = batch_prompt(project, batch, known_character_names);
        for attempt in 1..=3 {
            let mut received_chars = 0;
            let mut next_report_at = STREAM_PROGRESS_REPORT_CHARS;
            self.repository
                .update_drama_task_progress(task_id, progress, &stage)?;
            let response = self.providers.complete_with_web_search_content_stream(
                "language",
                model,
                &system,
                &prompt,
                enable_web,
                |delta| {
                    received_chars += delta.chars().count();
                    if received_chars >= next_report_at {
                        self.repository.update_drama_task_progress(
                            task_id,
                            progress,
                            &batch_stage(
                                batch,
                                batch_index,
                                batch_count,
                                received_chars,
                                completed_received_chars,
                            ),
                        )?;
                        next_report_at = received_chars + STREAM_PROGRESS_REPORT_CHARS;
                    }
                    Ok(())
                },
            );
            match response {
                Ok(value) => return Ok(value),
                Err(error) => {
                    let Some(delay) = immediate_language_retry_delay(&error, attempt) else {
                        return Err(AppError::External(format!("{stage}生成失败：{error}")));
                    };
                    self.repository.update_drama_task_progress(
                        task_id,
                        progress,
                        &format!(
                            "{stage}连接短暂异常，{} 秒后立即重试（{}/3）",
                            delay.as_secs(),
                            attempt + 1
                        ),
                    )?;
                    thread::sleep(delay);
                }
            }
        }
        unreachable!()
    }
}

/// Reserve the 65–75% range for verified decomposition progress, independent of batch size.
pub(super) fn batch_progress(completed_episodes: usize, total_episodes: usize) -> i64 {
    let total = total_episodes.max(1) as i64;
    let completed = (completed_episodes as i64).clamp(0, total);
    let range = DECOMPOSITION_END_PROGRESS - DECOMPOSITION_START_PROGRESS;
    DECOMPOSITION_START_PROGRESS + (range * completed + total / 2) / total
}

/// Describe the current durable batch and periodically report received model output without excessive SQLite writes.
pub(super) fn batch_stage(
    batch: &[support::Episode],
    batch_index: usize,
    batch_count: usize,
    batch_received_chars: usize,
    completed_received_chars: usize,
) -> String {
    let start = batch.first().map(|item| item.number).unwrap_or_default();
    let end = batch.last().map(|item| item.number).unwrap_or_default();
    let stage = format!(
        "第{start}至{end}集分镜骨架（第{}/{batch_count}批）",
        batch_index + 1
    );
    format!(
        "{stage}，累计已接收{}字（本批{}字）",
        completed_received_chars + batch_received_chars,
        batch_received_chars,
    )
}

fn batch_prompt(
    project: &Value,
    batch: &[support::Episode],
    known_character_names: &[String],
) -> String {
    let subtitles = project["shot_constraints"]["subtitles"]
        .as_bool()
        .unwrap_or(false);
    let music = project["shot_constraints"]["background_music"]
        .as_bool()
        .unwrap_or(false);
    let script = batch_source(batch);
    let known_characters = if known_character_names.is_empty() {
        "无（这是首批剧情）".to_owned()
    } else {
        known_character_names.join("、")
    };
    let web_search_instruction = if crate::value::bool_value(&project["enable_web_search"]) {
        "如需校验通用类型节奏，可使用 web_search；不得复制任何搜索到的作品内容。"
    } else {
        "仅依据本批剧本拆解；不得访问外部资料或使用任何联网检索能力。"
    };
    format!(
        "你正在生成长剧的分镜骨架。{web_search_instruction}只返回合法 JSON，不要 Markdown 或解释。顶层只能包含 episodes，禁止返回 assets；episode 有 name、shots；shot 有 title、original_text、prompt、duration、references；references 每项有 asset_type、asset_name，角色处于非基础形态时额外有 variant_name。\n必须且只能拆解第{:03}至第{:03}集，不得合并、遗漏或新增集数。每集生成2至4条按顺序衔接的分镜；每条分镜默认 duration 为 10 秒；original_text 不超过{}字，只能来自该集的局部事件，不能复制整集或整剧。references 必须逐镜列出实际出现的场景、角色、道具；若角色处于幼年、少年、成年、老年、伤病、变身、换装或其他外观明显不同的形态，必须填写对应 variant_name。每个 prompt 必须含有‘场景：’、‘角色：’、‘风格：’、‘光线：’、‘位置：’以及至少两个‘【镜头’段落，并使用 @图1（场景）、@图2（角色形态）、@图3（道具）形式预留参考图，文本需分段换行。不要在此请求中盘点或描述素材，素材目录由独立流程生成。\n项目创建配置：目标剧集数={}集；风格={}；题材={}；画幅={}；分辨率={}；分镜元素约束={}。{}{}\n人物首次出场规则：人物第一次在全剧清晰出场时，必须在其首个 original_text 保留或补写“【人物首次出场：当前名字｜人物描述：身份或关系、年龄/形态、2～3项稳定外观、当下情绪或动作】”，并同步写入 prompt 的对应镜头。该镜头还必须写入“【人物姓名标识｜姓名：当前名字｜时长：1～2s｜位置：人物近旁且不遮挡脸部｜效果：快速淡入淡出】”。姓名用当前剧情名；姓名标识不是字幕，即使关闭字幕也必须保留，且同一人物只在首次出场展示一次。此前批次已确认出场的角色：{known_characters}；这些角色不得重复标记为首次出场。\n本批剧本：\n{script}",
        batch[0].number,
        batch.last().map(|item| item.number).unwrap_or_default(),
        project["shot_script_max_chars"].as_i64().unwrap_or(400),
        project["episode_count"],
        project["style"].as_str().unwrap_or("真人风格"),
        project["theme"].as_str().unwrap_or("都市"),
        project["ratio"].as_str().unwrap_or("9:16"),
        project["resolution"].as_str().unwrap_or("720p"),
        project["shot_constraints"],
        if subtitles { "按剧情需要标注字幕信息。" } else { "不得出现字幕、屏幕文字或水印。" },
        if music { "可按剧情需要标注背景音乐。" } else { "不得出现背景音乐描述。" },
    )
}

/// Preserve the exact numbered script supplied to the model for later asset-evidence validation.
pub(super) fn batch_source(batch: &[support::Episode]) -> String {
    batch
        .iter()
        .map(|item| format!("【第{:03}集：{}】\n{}", item.number, item.title, item.body))
        .collect::<Vec<_>>()
        .join("\n\n")
}

/// Ask for a compact, batch-scoped material catalog separately from verbose storyboard output.
pub(super) fn asset_inventory_prompt(project: &Value, batch: &[support::Episode]) -> String {
    let script = batch_source(batch);
    format!(
        "只返回 JSON 对象 {{\"assets\":[...]}}，不要输出 episodes、shots、解释或 Markdown。请完整盘点下面第{:03}至第{:03}集实际出现的可复用素材：人物、发生剧情的空间、关键道具。每个 asset 字段必须有 type（character/scene/prop）、name、source_evidence、prompt；source_evidence 必须是本批剧本中逐字复制、不超过48字的连续原文，并同时包含 name。名称只能是该证据中的人物原名/稳定称谓、明确地点空间或具体物件；不得把对白、旁白、动作、情绪、时间天气、镜头术语或任意字串当成 name。证据无法证明实体类别时不得输出该项。不得设定每类 2 个或任何数量上限；不能遗漏有姓名或稳定称谓且参与剧情的人物、实际发生剧情的场景、被持有/使用/寻找/展示/推动剧情的物件。角色额外带 voice_id、variants；每个 variant 有 name、prompt、episode_numbers。只要剧本内同一角色存在幼年/少年/成年/老年、变身、伤病、明显换装或其他可视觉辨别形态，必须完整列入 variants，不能仅保留其中一个阶段；variant prompt 要明确此阶段的年龄、外貌、发型、体态、服饰与状态变化。每项 prompt 必须是该实体独立、可用于图片生成的描述：第一行写“叙述背景主题：{}”，第二行写“风格：{}”；角色写身份性格和稳定外观，场景写剧情用途、空间、陈设与无人物限制，道具写叙事用途、材质与呈现限制。\n\n本批剧本：\n{script}",
        batch[0].number,
        batch.last().map(|item| item.number).unwrap_or_default(),
        project["theme"].as_str().unwrap_or("都市"),
        project["style"].as_str().unwrap_or("真人风格"),
    )
}

pub(super) fn long_shots(raw: &Value, section: &support::Episode, project: &Value) -> Vec<Value> {
    let raw = raw["shots"]
        .as_array()
        .or_else(|| raw["storyboards"].as_array())
        .filter(|items| (2..=4).contains(&items.len()));
    let count = raw.map(Vec::len).unwrap_or(3);
    let segments = segments(
        &section.body,
        count,
        project["shot_script_max_chars"]
            .as_i64()
            .unwrap_or(400)
            .max(1) as usize,
    );
    (0..count).map(|index| { let item = raw.and_then(|items|items.get(index)).unwrap_or(&Value::Null); let prompt = item["prompt"].as_str().filter(|value|rich_prompt(value)).map(str::to_owned).unwrap_or_else(||fallback_prompt(section,&segments[index],index+1,project)); json!({"id":item["id"].as_str().unwrap_or(&format!("shot_{}_{}",section.number,index+1)),"title":item["title"].as_str().unwrap_or(&format!("第{}集镜头{}",section.number,index+1)),"original_text":segments[index],"prompt":prompt,"references":valid_references(&item["references"]),"duration_seconds":item["duration"].as_i64().or_else(||item["duration_seconds"].as_i64()).unwrap_or(10).clamp(3,15)}) }).collect()
}

fn segments(value: &str, count: usize, limit: usize) -> Vec<String> {
    let chars = value.chars().collect::<Vec<_>>();
    (0..count)
        .map(|index| {
            let start = chars.len() * index / count;
            let end = chars.len() * (index + 1) / count;
            chars[start..end]
                .iter()
                .collect::<String>()
                .chars()
                .take(limit)
                .collect()
        })
        .collect()
}
fn rich_prompt(value: &str) -> bool {
    [
        "场景：",
        "角色：",
        "风格：",
        "光线：",
        "位置：",
        "【镜头",
        "@图",
    ]
    .iter()
    .all(|part| value.contains(part))
}
fn fallback_prompt(
    _section: &support::Episode,
    segment: &str,
    index: usize,
    project: &Value,
) -> String {
    format!("场景：\n@图1（待匹配场景）\n\n角色：\n@图2（待匹配角色）\n\n道具：\n@图3（待匹配道具）\n\n风格：{}，叙述背景主题为{}，细节丰富。\n光线：根据当前剧情情绪设置自然且连续的主光。\n位置：@图2 位于画面主体区域，与 @图1 的空间关系清晰。\n\n【镜头{index} | 时长5s | 时间：按剧情】中景，平视，镜头稳定推进。@图2 {segment}\n【镜头{} | 时长5s | 时间：按剧情】近景，轻微推近，承接前一动作并留下下一镜线索。",project["style"].as_str().unwrap_or("真人风格"),project["theme"].as_str().unwrap_or("都市"),index+1)
}
pub(super) fn episode_number(item: &Value) -> Option<i64> {
    let value = item["name"].as_str().or_else(|| item["title"].as_str())?;
    let part = value.strip_prefix('第')?.trim_start();
    let number = part
        .chars()
        .take_while(char::is_ascii_digit)
        .collect::<String>()
        .parse()
        .ok()?;
    part.contains('集').then_some(number)
}
pub(super) fn valid_asset(item: &Value, evidence: &crate::planner::AssetEvidence) -> Option<Value> {
    let kind = match item["type"].as_str()?.trim() {
        "character" | "角色" => "character",
        "scene" | "场景" => "scene",
        "prop" | "道具" => "prop",
        _ => return None,
    };
    let name = evidence.canonical_name(
        kind,
        item["name"].as_str()?.trim(),
        item["source_evidence"].as_str().unwrap_or_default(),
    )?;
    let prompt = item["prompt"]
        .as_str()
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_owned)
        .unwrap_or_else(|| format!("剧本中出现的{kind}“{name}”，请保持其可复用的视觉连续性。"));
    (!name.is_empty()).then(|| json!({"id":item["id"],"type":kind,"name":name,"prompt":prompt,"voice_id":item["voice_id"],"variants":if kind == "character" { valid_variants(&item["variants"]) } else { Vec::new() },"status":NOT_GENERATED}))
}

fn valid_variants(items: &Value) -> Vec<Value> {
    let mut names = HashSet::new();
    items.as_array().into_iter().flatten().filter_map(|item| {
        let name = item["name"].as_str()?.trim();
        let prompt = item["prompt"].as_str()?.trim();
        (!name.is_empty() && !prompt.is_empty() && names.insert(name.to_owned())).then(|| json!({"id":item["id"],"name":name,"prompt":prompt,"episode_numbers":item["episode_numbers"]}))
    }).collect()
}

fn valid_references(items: &Value) -> Vec<Value> {
    items.as_array().into_iter().flatten().filter_map(|item| {
        let kind = item["asset_type"].as_str().or_else(|| item["type"].as_str())?.trim();
        let name = item["asset_name"].as_str().or_else(|| item["name"].as_str())?.trim();
        (["character", "scene", "prop"].contains(&kind) && !name.is_empty()).then(|| json!({"asset_type":kind,"asset_name":name,"variant_name":item["variant_name"].as_str().or_else(|| item["form_name"].as_str())}))
    }).collect()
}

pub(super) fn unique_assets(items: Vec<Value>) -> Vec<Value> {
    let mut unique = Vec::<Value>::new();
    for item in items {
        let existing = unique
            .iter_mut()
            .find(|current| current["type"] == item["type"] && current["name"] == item["name"]);
        let Some(existing) = existing else {
            unique.push(item);
            continue;
        };
        for variant in item["variants"].as_array().into_iter().flatten() {
            let Some(variants) = existing["variants"].as_array_mut() else {
                continue;
            };
            if !variants
                .iter()
                .any(|current| current["name"] == variant["name"])
            {
                variants.push(variant.clone());
            }
        }
    }
    unique
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::{batch_progress, batch_prompt, valid_asset};
    use crate::planner::AssetEvidence;
    use crate::worker::expansion::support::Episode;

    #[test]
    fn long_drama_batches_use_distinct_visible_progress() {
        assert_eq!(batch_progress(0, 25), 65);
        assert_eq!(batch_progress(3, 25), 66);
        assert_eq!(batch_progress(12, 25), 70);
        assert_eq!(batch_progress(24, 25), 75);
    }

    #[test]
    fn asset_names_survive_missing_model_prompts_and_chinese_types() {
        let evidence = AssetEvidence::from_script("赵峰抱着铁刀走进场景。");
        let asset = valid_asset(
            &json!({"type":"角色","name":"赵峰","source_evidence":"赵峰抱着铁刀"}),
            &evidence,
        )
        .expect("named model asset");
        assert_eq!(asset["type"], "character");
        assert_eq!(asset["name"], "赵峰");
        assert!(asset["prompt"]
            .as_str()
            .is_some_and(|text| !text.is_empty()));
    }

    #[test]
    fn rejects_dialogue_fragments_even_when_the_model_marks_them_as_scenes() {
        let script = "场景：村口石碑 正午 晴\n\"就是你这个外来灾星！带个外来瓜搅得全村不得安宁！\"陈大强举着红袖。";
        let evidence = AssetEvidence::from_script(script);

        assert!(valid_asset(
            &json!({"type":"scene","name":"就是你这个外来灾星","source_evidence":"就是你这个外来灾星！带个外来瓜搅得全村不得安宁！"}),
            &evidence,
        )
        .is_none());
        let scene = valid_asset(
            &json!({"type":"scene","name":"村口石碑","source_evidence":"场景：村口石碑 正午 晴"}),
            &evidence,
        )
        .expect("source-backed scene");
        assert_eq!(scene["name"], "村口石碑");
    }

    #[test]
    fn storyboard_prompt_only_mentions_web_search_when_the_project_enabled_it() {
        let batch = [Episode {
            number: 1,
            title: "开场".to_owned(),
            body: "场景：村口石碑 日\n林小满蹲在田埂啃西瓜。".to_owned(),
        }];
        let disabled = batch_prompt(&json!({"enable_web_search":false}), &batch, &[]);
        let enabled = batch_prompt(&json!({"enable_web_search":true}), &batch, &[]);

        assert!(!disabled.contains("web_search"));
        assert!(disabled.contains("仅依据本批剧本拆解"));
        assert!(disabled.contains("禁止返回 assets"));
        assert!(!disabled.contains("source_evidence"));
        assert!(enabled.contains("可使用 web_search"));
    }
}
